// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using hOps.web.Data;

#nullable disable

namespace hOps.web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251023144227_FlagExistingMustChangePassword")]
    partial class FlagExistingMustChangePassword
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");
#pragma warning restore 612, 618
        }
    }
}
